version: "3.7"
server:
  port:8888
services:
  myRetail:
    image: myretailapp
    ports:
      - "9080:8080"
    environment:
      - DOWNSTREAM_URI=https://ba1bc994-5c2c-4fe3-a51e-0a1d5bca3efe.mock.pstmn.io/productid/
