apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-retail
spec:
  replicas: 2
  selector:
    matchLabels:
     appname: myretail
  template:
    metadata:
      labels:
        appname: myretail
    spec:
      containers:
        - name: myretail
          image: myretailapp
          imagePullPolicy: IfNotPresent
          env:
            - name: DOWNSTREAM_URI
              value: https://ba1bc994-5c2c-4fe3-a51e-0a1d5bca3efe.mock.pstmn.io/productid/
          ports:
            - containerPort: 8888
